name: Docker build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: balujayatin/my-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
